name: app_initial
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  app_core:
    path: ../app_core
  app_helpers:
    path: ../app_helpers
  app_ui:
    path: ../app_ui
  cloud_firestore: ^5.6.0
  equatable: ^2.0.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_storage: ^12.3.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  go_router: ^14.6.2
  google_sign_in: ^6.2.2
  image_cropper: ^8.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  permission_handler: ^11.3.1
  reactive_forms: ^17.0.1
  shared_preferences: ^2.3.4
  sign_in_with_apple: ^6.1.4

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  generate: true
